---
- hosts: common
  vars:
    - os_packages:
        - git
        - gcc
        - libjpeg-devel
        - zlib-devel
    - python_packages:
        - Flask
        - boto3
        - jinja2
        - xhtml2pdf
    - project_name: "goPhoto"
  tasks:
    - name: "Update AWS config"
      file: dest=~/.aws state=directory
    - template:
        src: "templates/aws_config"
        dest: "~/.aws/config"
    - name: "Install common dependencies"
      yum: name={{item}}
      with_items: "{{os_packages}}"
      become: yes
    - name: "Install Python dependencies"
      pip: name={{item}}
      with_items: "{{python_packages}}"
      become: yes
    - name: "Synchronize repository"
      git:
        repo: https://github.com/Albert91/amazon-webservices.git
        dest: ~/{{project_name}}
        accept_hostkey: true
    - name: "Upload worker app config file"
      template:
        src: "~/config.py"
        dest: "~/{{project_name}}/src/worker/config.py"
        mode: 0600